# -*- coding: utf-8 -*-
"""
/***************************************************************************
 myplugin
                                 A QGIS plugin
 Does nothing yet.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-10-01
        git sha              : $Format:%H$
        copyright            : (C) 2018 by Papp Márton
        email                : pappmarci95@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import sys
from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication, QVariant
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction, QDialog, QWidget, QPushButton, QTextBrowser, QLabel, QVBoxLayout, QHBoxLayout, QLineEdit
from random import uniform, sample
from qgis.core import *

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .myplugin_dialog import mypluginDialog
import os.path



class myplugin:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'myplugin_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Create the dialog (after translation) and keep reference
        self.dlg = mypluginDialog()
        self.dlg.get_random.clicked.connect(lambda: self.random_feature_window())

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&myplugin')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'myplugin')
        self.toolbar.setObjectName(u'myplugin')

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('myplugin', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/myplugin/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u''),
            callback=self.run,
            parent=self.iface.mainWindow())


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&myplugin'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar










    def randpointlist(self, layer, pointnumber):
        lst = []
        ext = layer.extent()
        xmax = ext.xMaximum()
        xmin = ext.xMinimum()
        ymax = ext.yMaximum()
        ymin = ext.yMinimum()
        checkervalue = 0
        i = 1
        while i <= int(pointnumber):
            while True:
                x_coord = uniform(float(xmin), float(xmax))
                y_coord = uniform(float(ymin), float(ymax))
                randomPointGeometry = QgsGeometry.fromPointXY(QgsPointXY(x_coord, y_coord))
                for polygon in layer.getFeatures():
                    if polygon.geometry().contains(randomPointGeometry):
                       checkervalue = 1
                if checkervalue == 1:
                    lst.append([x_coord,  y_coord])
                    checkervalue = 0
                    break
                else:
                    pass
            i = i+1
        return lst



    def createpointlayer(self, nm, lst):
        layer = QgsVectorLayer("Point", str(nm), "memory")
        pr = layer.dataProvider()
        pr.addAttributes([QgsField("number", QVariant.String),
                          QgsField("x", QVariant.Double),
                          QgsField("y", QVariant.Double)])
        layer.updateFields()
        n = 1
        for list in lst:
            fet = QgsFeature()
            fet.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(list[0], list[1])))
            fet.setAttributes([str(n), list[0], list[1]])
            pr.addFeatures([fet])
            n = n+1
        layer.updateExtents()
        return layer










    def error_window(self, text_error):
        windw = QWidget()
        windw.setWindowTitle("Error Window")
        cancel_button = QPushButton()
        cancel_button.setText("Cancel")
        ok_button = QPushButton()
        ok_button.setText("Again")
        error_text = QTextBrowser()
        label = QLabel()
        label.setText("Press Again to restart the plugin GUI or Cancel to close plugin")
        vbox = QVBoxLayout()
        hbox = QHBoxLayout()
        ok_button.clicked.connect(lambda: self.error_window_ok(windw))
        cancel_button.clicked.connect(lambda: windw.close())
        error_text.append(text_error)
        vbox.addWidget(error_text)
        vbox.addStretch()
        vbox.addWidget(label)
        vbox.addStretch()
        hbox.addWidget(ok_button)
        hbox.addStretch()
        hbox.addWidget(cancel_button)
        hbox.addStretch()
        vbox.addLayout(hbox)
        windw.setLayout(vbox)
        windw.show()


    def error_window_ok(self, windw):
        windw.close()
        self.run()


    def number_check(self, n):
        try:
            float(n)
        except ValueError:
            return False









    def random_feature_window(self):
        windw = QWidget()
        windw.setWindowTitle("Random features")
        cancel_button = QPushButton()
        cancel_button.setText("Cancel")
        cancel_button.clicked.connect(lambda: windw.close())
        feature_text = QTextBrowser()
        number_label = QLabel()
        number_label.setText("Number of random features:")
        random_number = QLineEdit()
        get_features = QPushButton()
        get_features.setText("Get")
        get_features.clicked.connect(lambda: self.rand_features(random_number, feature_text))
        get_label = QLabel()
        get_label.setText("Get the random features:")
        hbox = QHBoxLayout()
        hbox.addWidget(number_label)
        hbox.addStretch()
        hbox.addWidget(random_number)
        hbox.addStretch()
        hbox2 = QHBoxLayout()
        hbox2.addWidget(get_label)
        hbox2.addStretch()
        hbox2.addWidget(get_features)
        hbox2.addStretch()
        vbox = QVBoxLayout()
        vbox.addLayout(hbox)
        vbox.addLayout(hbox2)
        vbox.addWidget(feature_text)
        vbox.addStretch()
        vbox.addWidget(cancel_button)
        vbox.addStretch()
        windw.setLayout(vbox)
        windw.show()

    def error_window_features(self, text_error):
        windw = QWidget()
        windw.setWindowTitle("Error Window")
        cancel_button = QPushButton()
        cancel_button.setText("Cancel")
        cancel_button.clicked.connect(lambda: windw.close())
        error_text = QTextBrowser()
        error_text.append(text_error)
        vbox = QVBoxLayout()
        vbox.addWidget(error_text)
        vbox.addStretch()
        vbox.addWidget(cancel_button)
        vbox.addStretch()
        windw.setLayout(vbox)
        windw.show()


    def rand_features(self, numb, text):
        text.clear()
        numb = numb.text()
        lay = self.iface.activeLayer()
        error_text = "The following error(s) occured:"
        error_1 = "A layer must be selected"
        error_2 = "The selected layer should have features"
        error_3 = "The number of the random features must be a number"
        error_4 = "The number of desired random features must be over zero"
        error_5 = "The number of random features should be an integer"
        error_6 = "The number of random features can't be over the amount of the layers features"
        precheckvalue = int()
        there_is_layer_value = int()
        if lay is not None:
            there_is_layer_value = there_is_layer_value + 1
        pre_feat_numb = int()
        there_isnt_features_value = int()
        if lay is not None:
            prefeats = lay.getFeatures()
            if prefeats is not None:
                for pref in prefeats:
                    pre_feat_numb = pre_feat_numb + 1
            else:
                there_isnt_features_value = there_isnt_features_value + 1
        else:
            there_isnt_features_value = there_isnt_features_value + 1
        is_number = self.number_check(numb)
        isnt_number_value = int()
        if lay is None:
            error_text = error_text + "\n" + error_1
            precheckvalue = precheckvalue + 1
        if there_is_layer_value == 1:
            if there_isnt_features_value == 1:
                error_text = error_text + "\n" + error_2
                precheckvalue = precheckvalue + 1
        if is_number == False:
            error_text = error_text + "\n" + error_3
            precheckvalue = precheckvalue + 1
            isnt_number_value = isnt_number_value + 1
        if isnt_number_value == 0:
            if float(numb) <= 0:
                error_text = error_text + "\n" + error_4
                precheckvalue = precheckvalue + 1
            if float(numb)-round(float(numb), 0) != 0:
                error_text = error_text + "\n" + error_5
                precheckvalue = precheckvalue + 1
            if there_isnt_features_value == 0:
                if float(numb) > pre_feat_numb:
                    error_text = error_text + "\n" + error_6
                    precheckvalue = precheckvalue + 1
        if precheckvalue != 0:
            " ".join(error_text)
            self.error_window_features(error_text)
        else:
            features = str()
            feats = lay.getFeatures()
            feat_numb = int(0)
            for x in feats:
                feat_numb = feat_numb + 1
            numb = int(numb)
            rand_list = list(range(1, feat_numb))
            rand_numb = sample(rand_list, numb)
            request = QgsFeatureRequest()
            request.setFilterFids(rand_numb)
            specific_features = lay.getFeatures(request)
            for fet in specific_features:
                feat_id = fet.id()
                feat_id = str(feat_id)
                feat = str(fet)
                feature_string = feat_id + ", " + feat + "\n"
                features = features + feature_string
            text.append(features)









    def randompointcreator(self):
        selected_layer = self.iface.activeLayer()
        pointnumber = self.dlg.point_number.text()
        nm = self.dlg.name_widget.text()
        error_print_text = "The following error(s) occured"
        error_1 = "Random point number should be a number"
        error_2 = "Random point number should be an integer"
        error_3 = "Random point number must be over zero"
        error_4 = "A layer should be selected"
        precheckvalue = int()
        isnt_number_value = int()
        is_number = self.number_check(pointnumber)
        if is_number == False:
            error_print_text = error_print_text + "\n" + error_1
            precheckvalue = precheckvalue + 1
            isnt_number_value = isnt_number_value + 1
        if isnt_number_value == 0:
            if float(pointnumber)-round(float(pointnumber), 0) != 0:
                error_print_text = error_print_text + "\n" + error_2
                precheckvalue = precheckvalue + 1
            if pointnumber <= 0:
                error_print_text = error_print_text + "\n" + error_3
                precheckvalue = precheckvalue + 1
        if selected_layer is None:
            error_print_text = error_print_text + "\n" + error_4
            precheckvalue = precheckvalue + 1
        if precheckvalue != 0:
            " ".join(error_print_text)
            self.error_window(error_print_text)
        else:
            lst = self.randpointlist(selected_layer, pointnumber)
            random_layer = self.createpointlayer(nm, lst)
            QgsProject.instance().addMapLayer(random_layer)



    def run(self):
        """Run method that performs all the real work"""
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            self.randompointcreator()
