# -*- coding: utf-8 -*-
"""
/***************************************************************************
 myplugin
                                 A QGIS plugin
 Does nothing yet.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-10-01
        copyright            : (C) 2018 by Papp Márton
        email                : pappmarci95@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load myplugin class from file myplugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .myplugin import myplugin
    return myplugin(iface)
